[versions]
# 版本号
constraintlayout-compose = "1.0.1"
constraintlayout-core = '1.0.4'
coordinatorlayout = '1.2.0'
customview = '1.1.0'
customview-poolingcontainer = '1.0.0'
# Androidx
# legacy [版本查询](https://www.wanandroid.com/maven_pom/index?k=androidx.legacy%3Alegacy-support-v4)
androidx-legacy = "1.0.0"
# core 相关 [版本查询](https://www.wanandroid.com/maven_pom/index?k=androidx.core)
androidx-core = "1.8.0"
# Compose 相关 [版本查询](https://www.wanandroid.com/maven_pom/index?k=androidx.compose)
androidx-compose = "1.0.0"
# activity 相关 [版本查询](https://www.wanandroid.com/maven_pom/index?k=androidx.activity)
androidx-activity = "1.5.1"
# Fragment 相关 [版本查询](https://www.wanandroid.com/maven_pom/index?k=androidx.fragment)
androidx-fragment = "1.5.1"
# 生命周期相关 [版本查询](https://www.wanandroid.com/maven_pom/index?k=androidx.lifecycle)
androidx-lifecycle = "2.5.1"
androidx-lifecycle-extensions = "2.2.0"
# Room 数据库相关 [版本查询](https://www.wanandroid.com/maven_pom/index?k=androidx.room)
androidx-room = "2.4.3"
androidx-room-coroutines = "2.1.0-alpha04"
# Paging 相关 [版本查询](https://www.wanandroid.com/maven_pom/index?k=androidx.paging)
androidx-paging = "3.1.1"
# Navigation 相关 [版本查询](https://www.wanandroid.com/maven_pom/index?k=androidx.navigation)
androidx-navigation = "2.5.1"
# WorkManager 相关 [版本查询](https://www.wanandroid.com/maven_pom/index?k=androidx.work)
androidx-work = "2.7.1"

# okhttp3 [Github](https://github.com/square/okhttp) [指南](https://square.github.io/okhttp)
squareup-okhttp3 = "4.10.0"
# Retrofit2 [Github](https://github.com/square/retrofit) [指南](https://square.github.io/retrofit/)
squareup-retrofit2 = "2.9.0"
# SmartRefreshLayout [Github](https://github.com/scwang90/SmartRefreshLayout)
scwang90-refresh = "2.0.5"
# 状态栏工具 [Github](https://github.com/gyf-dev/ImmersionBar)
geyifeng-immersionbar = "3.2.2"

[libraries]
# junit
test-junit = 'junit:junit:4.13.2'
test-ext = 'androidx.test.ext:junit:1.1.3'
test-espresso = 'androidx.test.espresso:espresso-core:3.4.0'
# Logger 日志打印 [Github](https://github.com/orhanobut/logger)
#orhanobut-logger = {group = ""}
androidx-appcompat = 'androidx.appcompat:appcompat:1.4.1'
androidx-appcompat-resources = 'androidx.appcompat:appcompat-resources:1.5.1'
androidx-recyclerview = 'androidx.recyclerview:recyclerview:1.2.1'
androidx-constraintlayout = 'androidx.constraintlayout:constraintlayout:2.1.3'
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }
androidx-constraintlayout-core = { module = "androidx.constraintlayout:constraintlayout-core", version.ref = "constraintlayout-core" }
androidx-activity = 'androidx.activity:activity:1.6.1'
androidx-activity-compose = 'androidx.activity:activity-compose:1.6.1'
androidx-fragment = 'androidx.fragment:fragment:1.5.5'
androidx-annotation = 'androidx.annotation:annotation:1.5.0'

coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
customview = { module = "androidx.customview:customview", version.ref = "customview" }
customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version.ref = "customview-poolingcontainer" }
# multidex 分包
androidx-multidex = 'androidx.multidex:multidex:2.0.1'

lifecycle-compiler = {module = 'androidx.lifecycle:lifecycle-compiler', version.ref = 'androidx-lifecycle'}
lifecycle-common = {module = 'androidx.lifecycle:lifecycle-common', version.ref = 'androidx-lifecycle'}
lifecycle-viewmodel = {module = 'androidx.lifecycle:lifecycle-viewmodel', version.ref = 'androidx-lifecycle'}
lifecycle-livedata = {module = 'androidx.lifecycle:lifecycle-livedata', version.ref = 'androidx-lifecycle'}
lifecycle-compose = {module = 'androidx.lifecycle:lifecycle-viewmodel-compose', version.ref = 'androidx-lifecycle'}
lifecycle-savedstate = {module = 'androidx.lifecycle:lifecycle-viewmodel-savedstate', version.ref = 'androidx-lifecycle'}
lifecycle-runtime = {module = 'androidx.lifecycle:lifecycle-runtime', version.ref = 'androidx-lifecycle'}
lifecycle-service = {module = 'androidx.lifecycle:lifecycle-service', version.ref = 'androidx-lifecycle'}
# Annotation processor
lifecycle-process = {module = 'androidx.lifecycle:lifecycle-process', version.ref = 'androidx-lifecycle'}
lifecycle-reactivestreams = {module = 'androidx.lifecycle:lifecycle-reactivestreams', version.ref = 'androidx-lifecycle'}
lifecycle-extensions = {module = 'androidx.lifecycle:lifecycle-extensions', version.ref = 'androidx-lifecycle-extensions'}

google-material = 'com.google.android.material:material:1.5.0'
google-gson = 'com.google.code.gson:gson:2.10'
# 腾讯相关
# MMKV [Github](https://github.com/tencent/mmkv)
tencent-mmkv = 'com.tencent:mmkv:1.2.14'
# Arouter [Github](https://github.com/alibaba/ARouter)
alibaba-arouter-api = 'com.alibaba:arouter-api:1.5.2'
alibaba-arouter-compiler = 'com.alibaba:arouter-compiler:1.5.2'
# Glide [Github](https://github.com/bumptech/glide)
#implementation 'com.github.bumptech.glide:glide:4.14.2'
#annotationProcessor 'com.github.bumptech.glide:compiler:4.14.2'
glide = 'com.github.bumptech.glide:glide:4.14.2'
glide-compiler = 'com.github.bumptech.glide:compiler:4.14.2'
# Logger 日志打印 [Github](https://github.com/orhanobut/logger)
logger = 'com.orhanobut:logger:2.2.0'

smartRefreshKernel = 'io.github.scwang90:refresh-layout-kernel:2.0.5'  # 核心必须依赖
smartRefreshHeader = 'io.github.scwang90:refresh-header-material:2.0.5'
smartRefreshFooter = 'io.github.scwang90:refresh-footer-classics:2.0.5'
loadsir = 'com.kingja.loadsir:loadsir:1.3.8'

[bundles]
androidx = ['androidx-appcompat', 'androidx-appcompat-resources', 'androidx-recyclerview', 'androidx-constraintlayout', 'androidx-constraintlayout-compose', 'androidx-constraintlayout-core', 'androidx-activity', 'androidx-activity-compose',
'androidx-fragment', 'androidx-annotation']
lifecycle = ['lifecycle-compiler', 'lifecycle-common', 'lifecycle-viewmodel', 'lifecycle-livedata', 'lifecycle-compose', 'lifecycle-savedstate', 'lifecycle-runtime',
'lifecycle-service', 'lifecycle-process', 'lifecycle-reactivestreams', 'lifecycle-extensions']
smartRefresh = ['smartRefreshKernel', 'smartRefreshHeader', 'smartRefreshFooter']